const adventureSideQuest = {
  title: 'What side quest might the characters encounter on their adventure?',
  description: 'You can also add one or more side quests to your adventure, taking the characters off the main story path defined by location or events. Side quests are peripheral to the characters’ primary goal, but successfully completing a side quest might provide a benefit toward completing the primary goal.',
  step: 'adventureSideQuest',
  previous: 'adventureTwist',
  highRange: 8,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Find a specific item rumored to be in the area',
      details: '',
      suggestedAdd: ' While adventuring, the heroes learn of a specific item rumored to be in the area that they could choose to try and find. ',
      next: 'adventureClimax',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Retrieve a stolen item in the villain’s possession',
      details: '',
      suggestedAdd: ' During their adventure, the heroes are presented with an opportunity to attempt to retrieve a stolen item in the villain\'s possession. ',
      next: 'adventureClimax',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Receive information from an NPC in the area',
      details: '',
      suggestedAdd: ' During their adventure, the heroes have a chance to pursue and recieve information from an NPC in the area should they choose to try. ',
      next: 'adventureClimax',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Rescue a captive',
      details: '',
      suggestedAdd: ' During their adventure, the heroes are presented with an opportunity to attempt to rescue a captive. ',
      next: 'adventureClimax',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Discover the fate of a missing NPC',
      details: '',
      suggestedAdd: ' During their adventure, the heroes are presented with a chance to discover the fate of a missing NPC. ',
      next: 'adventureClimax',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Slay a specific monster',
      details: '',
      suggestedAdd: ' During their adventure, the heroes have a chance to slay a specific monster should they choose to try. ',
      next: 'adventureClimax',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'Discover the nature and origin of a strange phenomenon in the area',
      details: '',
      suggestedAdd: ' While adventuring, the heroes might attempt to discover the nature and origin of a strange phenomenon in the area. ',
      next: 'adventureClimax',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Secure the aid of a character or creature in the area',
      details: '',
      suggestedAdd: ' During their adventure, the heroes are presented with a chance to secure the aid of a character or creature in the area. ',
      next: 'adventureClimax',
    },
  ],
};

module.exports = adventureSideQuest;
