const adventureClimax = {
  title: 'How does this adventure approach its climactic end?',
  description: 'The climactic ending of an adventure fulfills the promise of all that came before. Although the climax must hinge on the successes and failures of the characters up to that moment, the Adventure Climax table can provide suggestions to help you shape the end of your adventure.',
  step: 'adventureClimax',
  previous: 'adventureSideQuest',
  highRange: 12,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'The adventurers confront the main villain and a group of minions in a bloody battle to the finish',
      details: '',
      suggestedAdd: ' The adventure ends when the adventurers confront the main villain and a group of minions in a bloody battle to the finish. ',
      next: '',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'The adventurers chase the villain while dodging obstacles designed to thwart them, leading to a final confrontation in or outside the villain’s refuge',
      details: '',
      suggestedAdd: ' The adventure ends when the adventurers chase the villain while dodging obstacles designed to thwart them, leading to a final confrontation in or outside the villain’s refuge. ',
      next: '',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'The actions of the adventurers or the villain result in a cataclysmic event that the adventurers must escape',
      details: '',
      suggestedAdd: ' The adventure ends when the actions of the adventurers or the villain result in a cataclysmic event that the adventurers must escape. ',
      next: '',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'The adventurers race to the site where the villain is bringing a master plan to its conclusion, arriving just as that plan is about to be completed',
      details: '',
      suggestedAdd: ' The adventure ends when the adventurers race to the site where the villain is bringing a master plan to its conclusion, arriving just as that plan is about to be completed. ',
      next: '',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'The villain and two or three lieutenants perform separate rites in a large room. The adventurers must disrupt all the rites at the same time',
      details: '',
      suggestedAdd: ' The adventure ends when the villain and two or three lieutenants perform separate rites in a large room. The adventurers must disrupt all the rites at the same time. ',
      next: '',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'An ally betrays the adventurers as they’re about to achieve their goal',
      details: '',
      suggestedAdd: ' The adventure ends when an ally betrays the adventurers as they’re about to achieve their goal. ',
      next: '',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'A portal opens to another plane of existence. Creatures on the other side spill out, forcing the adventurers to close the portal and deal with the villain at the same time',
      details: '',
      suggestedAdd: ' The adventure ends when a portal opens to another plane of existence. Creatures on the other side spill out, forcing the adventurers to close the portal and deal with the villain at the same time. ',
      next: '',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Traps, hazards, or animated objects turn against the adventurers while the main villain attacks',
      details: '',
      suggestedAdd: ' The adventure ends when traps, hazards, or animated objects turn against the adventurers while the main villain attacks. ',
      next: '',
    },
    {
      lowRange: 9,
      highRange: 9,
      name: 'The dungeon begins to collapse while the adventurers face the main villain, who attempts to escape in the chaos',
      details: '',
      suggestedAdd: ' The adventure ends when the dungeon (or villain\'s lair) begins to collapse while the adventurers face the main villain, who attempts to escape in the chaos. ',
      next: '',
    },
    {
      lowRange: 10,
      highRange: 10,
      name: 'A threat more powerful than the adventurers appears, destroys the main villain, and then turns its attention on the characters',
      details: '',
      suggestedAdd: ' The adventure ends when a threat more powerful than the adventurers appears, destroys the main villain, and then turns its attention on the characters. ',
      next: '',
    },
    {
      lowRange: 11,
      highRange: 11,
      name: 'The adventurers must choose whether to pursue the fleeing main villain or save an NPC they care about or a group of innocents',
      details: '',
      suggestedAdd: ' The adventure ends when the adventurers must choose whether to pursue the fleeing main villain or save an NPC they care about or a group of innocents. ',
      next: '',
    },
    {
      lowRange: 12,
      highRange: 12,
      name: 'The adventurers must discover the main villain’s secret weakness before they can hope to defeat that villain',
      details: '',
      suggestedAdd: ' The adventure ends when the adventurers must discover the main villain’s secret weakness before they can hope to defeat that villain. ',
      next: '',
    },
  ],
};

module.exports = adventureClimax;
