const adventureAlly = {
  title: 'Who is an ally for the heroes on this adventure?',
  description: 'Heroes often have or need help along their way in an adventure.',
  step: 'adventureAlly',
  previous: 'villainWeakness',
  highRange: 12,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Skilled Adventurer',
      details: '',
      suggestedAdd: ' A skilled adventurer (at or slightly above the player characters\' level) assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Inexperienced Adventurer',
      details: '',
      suggestedAdd: ' An inexperienced adventurer (several levels or tiers below the characters\' level) assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Enthusiastic Commoner',
      details: '',
      suggestedAdd: ' An enthusiastic commoner assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Soldier',
      details: '',
      suggestedAdd: ' A soldier assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Priest',
      details: '',
      suggestedAdd: ' A priest assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Sage',
      details: '',
      suggestedAdd: ' A sage assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'Revenge Seeker',
      details: '',
      suggestedAdd: ' Someone seeking their own revenge assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Raving Lunatic',
      details: '',
      suggestedAdd: ' An raving lunatic assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 9,
      highRange: 9,
      name: 'Celestial Ally',
      details: '',
      suggestedAdd: ' A celestial ally assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 10,
      highRange: 10,
      name: 'Fey Ally',
      details: '',
      suggestedAdd: ' A fey ally assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 11,
      highRange: 11,
      name: 'Disguised Monster',
      details: '',
      suggestedAdd: ' A disguised monster seemingly assists the heroes in this adventure. ',
      next: 'adventurePatron',
    },
    {
      lowRange: 12,
      highRange: 12,
      name: 'Villain Posing as an Ally',
      details: '',
      suggestedAdd: ' The apparent ally of the heroes turns out to be the villain or an ally of the villain. ',
      next: 'adventurePatron',
    },
  ],
};

module.exports = adventureAlly;
