const adventureOtherGoals = {
  title: 'What are the heroes\' goals at the adventure\'s location?',
  description: 'The "Other Goals" table suggests location-based adventures that don\'t fit neatly into the categories of "Dungeon" or "Wilderness".  Many of these goals are suitable for locations in or around settlements.',
  step: 'adventureOtherGoals',
  previous: 'adventureType',
  highRange: 12,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Seize control of a fortified location such as a fortress, town, or ship',
      details: '',
      suggestedAdd: ' The heroes must seize control of a fortified location such as a fortress, town, or ship. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Defend a location from attackers',
      details: '',
      suggestedAdd: ' The heroes must defend a location from attackers. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Retrieve an object from inside a secure location in a settlement',
      details: '',
      suggestedAdd: ' The heroes seek to retrieve an object from inside a secure location in a settlement. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Retrieve an object from a caravan',
      details: '',
      suggestedAdd: ' The heroes must retrieve an object from a caravan. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Salvage an object or goods from a lost vessel or caravan',
      details: '',
      suggestedAdd: ' The heroes need to salvage an object or goods from a lost vessel or caravan. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Break a prisoner out of a jail or prison camp',
      details: '',
      suggestedAdd: ' The heroes must attempt to break a prisoner out of a jail or prison camp. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'Escape from a jail or prison camp',
      details: '',
      suggestedAdd: ' The heroes must escape from a jail or prison camp. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Successfully travel through an obstacle course to gain recognition or reward',
      details: '',
      suggestedAdd: ' The heroes must try to successfully travel through an obstacle course to gain recognition or reward. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 9,
      highRange: 9,
      name: 'Infiltrate a fortified location',
      details: '',
      suggestedAdd: ' The heroes must infiltrate a fortified location. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 10,
      highRange: 10,
      name: 'Find the source of strange occurrences in a haunted house or other location',
      details: '',
      suggestedAdd: ' The heroes seek to find the source of strange occurrences in a haunted house or other location. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 11,
      highRange: 11,
      name: 'Interfere with the operation of a business',
      details: '',
      suggestedAdd: ' The heroes try to interfere with the operation of a business. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 12,
      highRange: 12,
      name: 'Rescue a character, monster, or object from a natural or unnatural disaster',
      details: '',
      suggestedAdd: ' The heroes must attempt to rescue a character, monster, or object from a natural or unnatural disaster. ',
      next: 'adventureVillain',
    },
  ],
};

module.exports = adventureOtherGoals;
