const adventureWildernessGoals = {
  title: 'What are the heroes\' goals in the wilderness?',
  description: 'The following table provides common goals that drive or lure adventurers into an adventure focused on outdoor exploration',
  step: 'adventureWildernessGoals',
  previous: 'adventureType',
  highRange: 20,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Locate a dungeon or other site of interest (roll on the Dungeon Goals table to find out why)',
      details: '',
      suggestedAdd: ' The heroes need to explore the wilds to locate a dungeon or other site of interest. ',
      next: 'adventureDungeonGoals',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Assess the scope of a natural or unnatural disaster',
      details: '',
      suggestedAdd: ' The heroes need to explore the wilds to assess the scope of a natural or unnatural disaster. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Escort an NPC to a destination',
      details: '',
      suggestedAdd: ' The heroes must escort an NPC through the wilderness to a destination. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Arrive at a destination without being seen by the villain’s forces',
      details: '',
      suggestedAdd: ' The heroes must travel the wilds to arrive at a destination without being seen by the villain’s forces. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Stop monsters from raiding caravans and farms',
      details: '',
      suggestedAdd: ' The heroes must stop monsters living in the wilderness from raiding caravans and farms. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Establish trade with a distant town',
      details: '',
      suggestedAdd: ' The heroes must traverse the wilds to establish trade with a distant town. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'Protect a caravan traveling to a distant town',
      details: '',
      suggestedAdd: ' The heroes must protect a caravan traveling through the wilds to a distant town. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Map a new land',
      details: '',
      suggestedAdd: ' The heroes need to explore the wilds to map a new land. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 9,
      highRange: 9,
      name: 'Find a place to establish a colony',
      details: '',
      suggestedAdd: ' The heroes must search the wilds to find a place to establish a colony. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 10,
      highRange: 10,
      name: 'Find a natural resource',
      details: '',
      suggestedAdd: ' The heroes are exploring the wilds in order to find a natural resource. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 11,
      highRange: 11,
      name: 'Hunt a specific monster',
      details: '',
      suggestedAdd: ' The heroes must navigate the wilds to hunt a specific monster. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 12,
      highRange: 12,
      name: 'Return home from a distant place',
      details: '',
      suggestedAdd: ' The heroes must navigate the wilderness to return home from a distant place. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 13,
      highRange: 13,
      name: 'Obtain information from a reclusive hermit',
      details: '',
      suggestedAdd: ' The heroes must search the wilds to obtain information from a reclusive hermit. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 14,
      highRange: 14,
      name: 'Find an object that was lost in the wilds',
      details: '',
      suggestedAdd: ' The heroes need to find an object that was lost in the wilds.',
      next: 'adventureVillain',
    },
    {
      lowRange: 15,
      highRange: 15,
      name: 'Discover the fate of a missing group of explorers',
      details: '',
      suggestedAdd: ' The heroes must search the wilds to discover the fate of a missing group of explorers. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 16,
      highRange: 16,
      name: 'Pursue fleeing foes.',
      details: '',
      suggestedAdd: ' The heroes must navigate the wilds to pursue fleeing foes. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 17,
      highRange: 17,
      name: 'Assess the size of an approaching army',
      details: '',
      suggestedAdd: ' The heroes must scout the wilds to assess the size of an approaching. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 18,
      highRange: 18,
      name: 'Escape the reign of a tyrant',
      details: '',
      suggestedAdd: ' The heroes must travel the wilds to escape the reign of a tyrant. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 19,
      highRange: 19,
      name: 'Protect a wilderness site from attackers',
      details: '',
      suggestedAdd: ' The heroes must navigate the wilds to protect a wilderness site from attackers. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 20,
      highRange: 20,
      name: 'Roll twice, ignoring results of 20',
      details: '',
      suggestedAdd: '',
      next: 'adventureVillain',
    },
  ],
};

module.exports = adventureWildernessGoals;
