const tableTitle = {
  title: 'What Events Set the Frame for the Intrigue?',
  description: 'You can base an entire adventure on a framing event or use such an event to grab the players\' interest.  The following table presents several ideas, or you can use it to inspire your own framing event.',
  step: 'adventureFramingEvents',
  previous: 'adventureType',
  rows: [
    {
      lowRange: 1,
      highRange: 2,
      name: 'Anniversary of a monarch’s reign',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during the anniversary of the monarch\'s reign. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 3,
      highRange: 4,
      name: 'Anniversary of an important event',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during the  anniversary of an important event.',
      next: 'adventureVillain',
    },
    {
      lowRange: 5,
      highRange: 6,
      name: 'Arena event',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during an arena event. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 7,
      highRange: 8,
      name: 'Arrival of a caravan or ship',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue upon the arrival of a caravan or ship.',
      next: 'adventureVillain',
    },
    {
      lowRange: 9,
      highRange: 10,
      name: 'Arrival of a circus',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue when a circus arrives.',
      next: 'adventureVillain',
    },
    {
      lowRange: 11,
      highRange: 12,
      name: 'Arrival of an important NPC',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue upon the arrival of an important NPC. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 13,
      highRange: 14,
      name: 'Arrival of marching modrons',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue resulting from the surprise caused by the arrival of marching modrons. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 15,
      highRange: 16,
      name: 'Artistic performance',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue surrounding an artistic performance .',
      next: 'adventureVillain',
    },
    {
      lowRange: 17,
      highRange: 18,
      name: 'Athletic event',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue occuring during an athletic event. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 19,
      highRange: 20,
      name: 'Birth of a child',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during the birth of a child. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 21,
      highRange: 22,
      name: 'Birthday of an important NPC',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during the birthday of an important NPC. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 23,
      highRange: 24,
      name: 'Civic festival',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during a civic festival. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 25,
      highRange: 26,
      name: 'Comet appearance',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue after the appearance of an ominous comet. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 27,
      highRange: 28,
      name: 'Commemoration of a past tragedy',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during the commemoration of a past tragedy. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 29,
      highRange: 30,
      name: 'Consecration of a new temple',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue upon the occasion of the consecration of a new temple. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 31,
      highRange: 32,
      name: 'Coronation',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during the coronation of a new royal. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 33,
      highRange: 34,
      name: 'Council meeting',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during a gathering of advisors for a council meeting. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 35,
      highRange: 36,
      name: 'Equinox or solstice',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during the Equinox or solstice. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 37,
      highRange: 38,
      name: 'Execution',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue surrounding an execution. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 39,
      highRange: 40,
      name: 'Fertility festival',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue running through a fertility festival. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 41,
      highRange: 42,
      name: 'Full moon',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue under the auspices of a full moon. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 43,
      highRange: 44,
      name: 'Funeral',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue callously surrounding a funeral. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 45,
      highRange: 46,
      name: 'Graduation of cadets or wizards',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue during the graduation of cadets or wizards. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 47,
      highRange: 48,
      name: 'Harvest festival',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during the celebration of the harvest festival. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 49,
      highRange: 50,
      name: 'Holy day',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue occuring during the observance of a holy day. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 51,
      highRange: 52,
      name: 'Investiture of a knight or other noble',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue surrounding the investiture of a knight or other noble. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 53,
      highRange: 54,
      name: 'Lunar eclipse',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue under the auspices of a lunar eclipse. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 55,
      highRange: 58,
      name: 'Midsummer festival',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue occuring during the midsummer festival. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 59,
      highRange: 60,
      name: 'Midwinter festival',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue occuring during the midwinter festival. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 61,
      highRange: 62,
      name: 'Migration of monsters',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue during the migration of monsters. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 63,
      highRange: 64,
      name: 'Monarch’s ball',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue made possible by the monarch\'s ball. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 65,
      highRange: 66,
      name: 'New moon',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue under the lightless auspices of a new moon. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 67,
      highRange: 68,
      name: 'New year',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during the celebration of the new year. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 69,
      highRange: 70,
      name: 'Pardoning of a prisoner',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue surrounding the pardoning of a prisoner. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 71,
      highRange: 72,
      name: 'Planar conjunction',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue during an ominous planar conjunction. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 73,
      highRange: 74,
      name: 'Planetary alignment',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue during an ominous planetary alignment. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 75,
      highRange: 76,
      name: 'Priestly investiture',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue surrounding a priestly investiture. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 77,
      highRange: 78,
      name: 'Procession of ghosts',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue occasioned by the procession of ghosts. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 79,
      highRange: 80,
      name: 'Remembrance for soldiers lost in war',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue occuring during the remembrance for soldiers lost in war. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 81,
      highRange: 82,
      name: 'Royal address or proclamation',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue during the royal address or proclamation. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 83,
      highRange: 84,
      name: 'Royal audience day',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue which regularly occurs during the royal audience day. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 85,
      highRange: 86,
      name: 'Signing of a treaty',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue surrounding the signing of a treaty. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 87,
      highRange: 88,
      name: 'Solar eclipse',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue under the auspices of a solar eclipse. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 89,
      highRange: 90,
      name: 'Tournament',
      details: '',
      suggestedAdd: ' The heroes are pulled into intrigue occasioned by the hosting of a tournament. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 91,
      highRange: 94,
      name: 'Trial',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue surrounding a trial. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 95,
      highRange: 96,
      name: 'Violent uprising',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue caused by a violent uprising. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 97,
      highRange: 98,
      name: 'Wedding or wedding anniversary',
      details: '',
      suggestedAdd: ' The heroes are pulled into the intrigue occasioned by a wedding or wedding anniversary. ',
      next: 'adventureVillain',
    },
    {
      lowRange: 99,
      highRange: 100,
      name: 'Concurrence of two events (roll twice, ignoring results of 99 or 100)',
      details: '',
      suggestedAdd: '',
      next: 'adventureVillain',
    },
  ],
};

module.exports = tableTitle;
