const villainMethodCoercion = {
  title: 'What means of captivity or coercion does the villain use?',
  description: '',
  step: 'villainMethodCoercion',
  previous: 'villainMethod',
  highRange: 20,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Bribery',
      details: '',
      suggestedAdd: ' The villain pursues their goals via bribery. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Enticement',
      details: '',
      suggestedAdd: ' The villain pursues their goals via enticement. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Eviction',
      details: '',
      suggestedAdd: ' The villain pursues their goals via eviction. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Imprisonment',
      details: '',
      suggestedAdd: ' The villain pursues their goals via imprisonment. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Kidnapping',
      details: '',
      suggestedAdd: ' The villain pursues their goals via kidnapping. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Legal Intimidation',
      details: '',
      suggestedAdd: ' The villain pursues their goals via legal intimidation. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'Press Gangs',
      details: '',
      suggestedAdd: ' The villain pursues their goals via press gangs. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Shackling',
      details: '',
      suggestedAdd: ' The villain pursues their goals via shackling. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 9,
      highRange: 9,
      name: 'Slavery',
      details: '',
      suggestedAdd: ' The villain pursues their goals via slavery. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 10,
      highRange: 10,
      name: 'Threats or Harassment',
      details: '',
      suggestedAdd: ' The villain pursues their goals via threats or harassment. ',
      next: 'villainWeakness',
    },
  ],
};

module.exports = villainMethodCoercion;
