const villainMethodTorture = {
  title: 'What form of torture does the villain use?',
  description: '',
  step: 'villainMethodTorture',
  previous: 'villainMethod',
  highRange: 6,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Acid',
      details: '',
      suggestedAdd: ' The villain tortures people with acid in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Blinding',
      details: '',
      suggestedAdd: ' In pursuit of their goals, the villain tortures people by blinding them. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Branding',
      details: '',
      suggestedAdd: ' In pursuit of their goals, the villain marks and tortures people by branding them. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Racking',
      details: '',
      suggestedAdd: ' In pursuit of their goals, the villain puts people in the torture rack. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Thumbscrews',
      details: '',
      suggestedAdd: ' The villain tortures people with thumbscrews as a means of pursuing their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Whipping',
      details: '',
      suggestedAdd: ' The villain whips people, torturing them in pursuit of their goals. ',
      next: 'villainWeakness',
    },
  ],
};

module.exports = villainMethodTorture;
