const villainMethodMurder = {
  title: 'What form of murder does the villain use to achieve their goals?',
  description: '',
  step: 'villainMethodMurder',
  previous: 'villainMethod',
  highRange: 8,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Assassination',
      details: '',
      suggestedAdd: ' The villain uses assassination in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Cannibalism',
      details: '',
      suggestedAdd: ' The villain canibalizes those they murder in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Dismemberment',
      details: '',
      suggestedAdd: ' The villain dismembers those they murder in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Drowning',
      details: '',
      suggestedAdd: ' The villain drowns those they murder in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Electrocution',
      details: '',
      suggestedAdd: ' The villain electrocutes those they murder in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Euthanasia (involuntary)',
      details: '',
      suggestedAdd: ' The villain uses involuntary euthanasia in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'Disease',
      details: '',
      suggestedAdd: ' The villain uses murderous disease(s) in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Poisoning',
      details: '',
      suggestedAdd: ' The villain poisons those they murder in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 9,
      highRange: 9,
      name: 'Stabbing',
      details: '',
      suggestedAdd: ' The villain stabs those they murder in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 10,
      highRange: 10,
      name: 'Strangulation or Suffocation',
      details: '',
      suggestedAdd: ' The villain suffocates or strangles those they murder in pursuit of their goals. ',
      next: 'villainWeakness',
    },
  ],
};

module.exports = villainMethodMurder;
