const villainSchemeMayhem = {
  title: 'What is the villain\'s scheme for causing mayhem?',
  description: 'Some villain\'s just want to watch the world burn...',
  step: 'villainSchemeMayhem',
  previous: 'villainScheme',
  highRange: 6,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Fulfill an apocalyptic prophecy',
      details: '',
      suggestedAdd: ' The villain wants to cause mayhem by fulfilling an apocalyptic prophecy. ',
      next: 'villainMethod',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Enact the vengeful will of a god or patron',
      details: '',
      suggestedAdd: ' The villain wants to enact the vengeful will of a god or patron, which will lead to widespread destruction. ',
      next: 'villainMethod',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Spread a vile contagion',
      details: '',
      suggestedAdd: ' The villain seeks to create mayhem through spreading a vile contagion. ',
      next: 'villainMethod',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Overthrow a government',
      details: '',
      suggestedAdd: ' The villain seeks to create chaos through overthrowing a government. ',
      next: 'villainMethod',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Trigger a natural disaster',
      details: '',
      suggestedAdd: ' The villain seeks to create widespread destruction by triggering a natural disaster. ',
      next: 'villainMethod',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Utterly destroy a bloodline or clan',
      details: '',
      suggestedAdd: ' The villain pursues the total destruction of a bloodline or clan, which would result in chaos. ',
      next: 'villainMethod',
    },
  ],
};

module.exports = villainSchemeMayhem;
