const villainSchemeMagic = {
  title: 'What is the villain\'s scheme for gaining magical power?',
  description: '',
  step: 'villainSchemeMagic',
  previous: 'villainScheme',
  highRange: 6,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Obtain an ancient artifact',
      details: '',
      suggestedAdd: ' The villain is seeking to obtain an ancient and powerful magical artifact. ',
      next: 'villainMethod',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Build a construct or magical device',
      details: '',
      suggestedAdd: ' The villain is seeking to build a dangerous magical construct or device. ',
      next: 'villainMethod',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Carry out a deity\'s wishes',
      details: '',
      suggestedAdd: ' The villain is seeking to gain magical might through carrying out a deity\'s wishes. ',
      next: 'villainMethod',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Offer sacrifices to a deity',
      details: '',
      suggestedAdd: ' The villain is seeking to gain magical power by offering sacrifices to a deity. ',
      next: 'villainMethod',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Contact a lost deity or power',
      details: '',
      suggestedAdd: ' The villain is trying to contact a lost deity or power to gain access to powerful magics. ',
      next: 'villainMethod',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Open a gate to another world',
      details: '',
      suggestedAdd: ' The villain is seeking to gain powerful magic by opening a gateway to another world. ',
      next: 'villainMethod',
    },
  ],
};

module.exports = villainSchemeMagic;
