const villainMethodMagic = {
  title: 'What means of magical mayhem does the villain use to achieve their goals?',
  description: '',
  step: 'villainMethodMagic',
  previous: 'villainMethod',
  highRange: 8,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Hauntings',
      details: '',
      suggestedAdd: ' The villain uses magical hauntings in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Illusions',
      details: '',
      suggestedAdd: ' The villain uses magical illusions in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Infernal Bargains',
      details: '',
      suggestedAdd: ' The villain uses infernal bargains in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Mind Control',
      details: '',
      suggestedAdd: ' The villain uses mind control in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Petrification',
      details: '',
      suggestedAdd: ' The villain uses magical petrification in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Raising or Animating the Dead',
      details: '',
      suggestedAdd: ' The villain uses necromancy in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'Summoning Monsters',
      details: '',
      suggestedAdd: ' The villain magically summons monsters in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Weather Control',
      details: '',
      suggestedAdd: ' The villain uses magic to control the weather in pursuit of their goals. ',
      next: 'villainWeakness',
    },
  ],
};

module.exports = villainMethodMagic;
