const villlainMethod = {
  title: 'How will the villain go about achieving their goal(s)?',
  description: '',
  step: 'villlainMethod',
  previous: 'villainScheme',
  highRange: 20,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Agricultural Devastation',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodAgriculture',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Assault or Beatings',
      details: '',
      suggestedAdd: ' The villain pursues their goals via assault or beatings. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Bounty hunting or assassination',
      details: '',
      suggestedAdd: ' The villain pursues their goals via bounty hunting or assassination. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Captivity or coercion',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodCoercion',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Confidence scams',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodScam',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Defamation',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodDefamation',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'Dueling',
      details: '',
      suggestedAdd: 'The villain pursues their goals via dueling.',
      next: 'villainWeakness',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Execution',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodExecution',
    },
    {
      lowRange: 9,
      highRange: 9,
      name: 'Impersonation or Disguise',
      details: '',
      suggestedAdd: ' The villain pursues their goals via impersonation or disguise. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 10,
      highRange: 10,
      name: 'Lying or Perjury',
      details: '',
      suggestedAdd: ' The villain pursues their goals via lying or perjury. ',
      next: 'villainMethodPerjury',
    },
    {
      lowRange: 11,
      highRange: 11,
      name: 'Magical Mayhem',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodMagic',
    },
    {
      lowRange: 12,
      highRange: 12,
      name: 'Murder',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodMurder',
    },
    {
      lowRange: 13,
      highRange: 13,
      name: 'Neglect',
      details: '',
      suggestedAdd: ' Paradoxically, the villain pursues their goals by means of neglect. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 14,
      highRange: 14,
      name: 'Politics',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodPolitics',
    },
    {
      lowRange: 15,
      highRange: 15,
      name: 'Religion',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodReligion',
    },
    {
      lowRange: 16,
      highRange: 16,
      name: 'Stalking',
      details: '',
      suggestedAdd: ' The villain pursues their goals by stalking. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 17,
      highRange: 17,
      name: 'Theft / Property Crime',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodTheft',
    },
    {
      lowRange: 18,
      highRange: 18,
      name: 'Torture',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodTorture',
    },
    {
      lowRange: 19,
      highRange: 19,
      name: 'Vice',
      details: '',
      suggestedAdd: 'villainMethodVice',
      next: 'villainMethodVice',
    },
    {
      lowRange: 20,
      highRange: 20,
      name: 'Warfare',
      details: '',
      suggestedAdd: '',
      next: 'villainMethodWarfare',
    },
  ],
};

module.exports = villlainMethod;
