const villainMethodTheft = {
  title: 'What form of theft does the villain use to achieve their goals?',
  description: '',
  step: 'villainMethodTheft',
  previous: 'villainMethod',
  highRange: 10,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Arson',
      details: '',
      suggestedAdd: ' The villain uses arson in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Blackmail or Extortion',
      details: '',
      suggestedAdd: ' The villain uses blackmail or extortion in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Dismemberment',
      details: '',
      suggestedAdd: ' The villain commits burglary in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Drowning',
      details: '',
      suggestedAdd: ' The villain engages in counterfeiting in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Electrocution',
      details: '',
      suggestedAdd: ' The villain engaegs in highway robbery in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Euthanasia (involuntary)',
      details: '',
      suggestedAdd: ' The villain engages in looting in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'Disease',
      details: '',
      suggestedAdd: ' The villain mugs people in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Poisoning',
      details: '',
      suggestedAdd: ' The villain engages in poaching in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 9,
      highRange: 9,
      name: 'Stabbing',
      details: '',
      suggestedAdd: ' The villain seizes other\'s property in pursuit of their goals. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 10,
      highRange: 10,
      name: 'Strangulation or Suffocation',
      details: '',
      suggestedAdd: ' The villain smuggles people or goods in pursuit of their goals. ',
      next: 'villainWeakness',
    },
  ],
};

module.exports = villainMethodTheft;
