const villainMethodScam = {
  title: 'What type of con or scam does the villain use?',
  description: '',
  step: 'villainMethodScam',
  previous: 'villainMethod',
  highRange: 6,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Breach of Contract',
      details: '',
      suggestedAdd: ' The villain pursues their goals via breach of contract. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Cheating',
      details: '',
      suggestedAdd: ' The villain pursues their goals by cheating. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Fast Talking',
      details: '',
      suggestedAdd: ' The villain pursues their goals through fast talking. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Fine Print',
      details: '',
      suggestedAdd: ' The villain pursues their goals by abusing the fine print in negotiations. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Fraud or Swindling',
      details: '',
      suggestedAdd: ' The villain pursues their goals via fraud or swindling. ',
      next: 'villainWeakness',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Quackery or Tricks',
      details: '',
      suggestedAdd: ' The villain pursues their goals via quackery or tricks. ',
      next: 'villainWeakness',
    },
  ],
};

module.exports = villainMethodScam;
