const villainScheme = {
  title: 'What does the villain want?',
  description: '',
  step: 'villainScheme',
  previous: 'adventureVillain',
  highRange: 8,
  source: 'DMG',
  rows: [
    {
      lowRange: 1,
      highRange: 1,
      name: 'Immortality',
      details: '',
      suggestedAdd: '',
      next: 'villainSchemeImmortality',
    },
    {
      lowRange: 2,
      highRange: 2,
      name: 'Influence',
      details: '',
      suggestedAdd: '',
      next: 'villainSchemeInfluence',
    },
    {
      lowRange: 3,
      highRange: 3,
      name: 'Magic',
      details: '',
      suggestedAdd: '',
      next: 'villainSchemeMagic',
    },
    {
      lowRange: 4,
      highRange: 4,
      name: 'Mayhem',
      details: '',
      suggestedAdd: '',
      next: 'villainSchemeMayhem',
    },
    {
      lowRange: 5,
      highRange: 5,
      name: 'Passion',
      details: '',
      suggestedAdd: '',
      next: 'villainSchemePassion',
    },
    {
      lowRange: 6,
      highRange: 6,
      name: 'Power',
      details: '',
      suggestedAdd: '',
      next: 'villainSchemePower',
    },
    {
      lowRange: 7,
      highRange: 7,
      name: 'Revenge',
      details: '',
      suggestedAdd: '',
      next: 'villainSchemeRevenge',
    },
    {
      lowRange: 8,
      highRange: 8,
      name: 'Wealth',
      details: '',
      suggestedAdd: '',
      next: 'villainSchemeWealth',
    },
  ],
};

module.exports = villainScheme;
